### ISSUE TITLE
Add more information about flash firmware

### ISSUE THREAD

**Issue by MarkKoshelev** [Harwesta/beeline_sbtplus#1]
Some questions:
_For others
Download appropriate -factory.zip or -sysupgrade.bin firmware.__

What is differences in the firmwares? What is preffered?

_Check partiton table on your router patrtition start size u-boot 0x0-0x100000, SC PART_MAP 0x100000-0x100000, kernel 0x200000-0x400000, ubi 0x600000-0x7800000, factory 0x7e00000-0x100000_

How to check the partiton table?

_Flash firmware._

How flash the  firmware?

**Comment by Harwesta** [comment]
Сomments added to README file
