### ISSUE TITLE
patch file is incopatible with branch openwrt-22.03

### ISSUE THREAD

**Issue by MarkKoshelev** [Harwesta/beeline_sbtplus#3]
oper@ubuntu22$ patch -p1 < beeline_sbtpluslus_uart3_hsdma_2021-01-25.patch
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -ruN target/linux/ramips/base-files/etc/board.d/02_network target/linux/ramips/base-files/etc/board.d/02_network
|--- target/linux/ramips/base-files/etc/board.d/02_network      2021-01-25 09:29:08.901370257 +0500
|+++ target/linux/ramips/base-files/etc/board.d/02_network      2021-01-18 11:25:53.756674000 +0500

**Comment by Harwesta** [comment]
This patch is intended for openwrt version 19.x, and I'm not going to adapt it for each subsequent release.
I specifically upload separate files in the repository to set up the environment for this router:
02_network, platform.sh, .dts + .dtsi file, mt7621.mk

**Comment by MarkKoshelev** [comment]
Can you fix readme for branch openwrt-22.03?
_Configuration files & patches for Beeline Smart Box Turbo+ Openwrt firmware_
