### ISSUE TITLE
UART3 problem

### ISSUE THREAD

**Issue by MarkKoshelev** [Harwesta/beeline_sbtplus#4]
after upgarade to openwrt22.03.2-beeline_sbtplus-factory-Netgear.zip
cat /dev/ttyS1
cat: read error: I/O error

**Comment by Harwesta** [comment]
The name of the interfaces was changed when openwrt moving up from version 19 to version 22. This has been fixed in version 22.03.3.
Please use the pre-compiled version of the firmware.

**Comment by Harwesta** [comment]
Files added
